# Generated by Django 3.1.4 on 2020-12-20 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('due_at', models.DateTimeField(blank=True, verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.accounts')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.channels')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationsReplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replied_at', models.DateTimeField(verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.accounts')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.conversations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.users')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationsRecepients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField()),
                ('replied', models.BooleanField()),
                ('closed', models.BooleanField()),
                ('last_replied_at', models.DateTimeField(verbose_name='date')),
                ('closed_at', models.DateTimeField(verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.accounts')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.conversations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.users')),
            ],
        ),
        migrations.AddField(
            model_name='conversations',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.users'),
        ),
        migrations.AddField(
            model_name='channels',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.users'),
        ),
        migrations.CreateModel(
            name='AdminReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_new_conversations', models.IntegerField(blank=True, default=0)),
                ('weekly_new_conversations', models.IntegerField(blank=True, default=0)),
                ('daily_new_conversations', models.IntegerField(blank=True, default=0)),
                ('monthly_replied_conversations', models.IntegerField(default=0)),
                ('weekly_replied_conversations', models.IntegerField(default=0)),
                ('daily_replied_conversations', models.IntegerField(default=0)),
                ('monthly_closed_conversations', models.IntegerField(default=0)),
                ('weekly_closed_conversations', models.IntegerField(default=0)),
                ('daily_closed_conversations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.accounts')),
            ],
        ),
    ]
