# Generated by Django 3.1.4 on 2020-12-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users',
            unique_together={('account', 'email')},
        ),
    ]
